import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1782667745043 implements MigrationInterface {
    name = 'InitSchema1782667745043'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "prefix" character varying NOT NULL, "code" BIGSERIAL NOT NULL, "slug" character varying(150) NOT NULL, "description" text, "country" jsonb, "websiteUrl" character varying(255) NOT NULL, "logoUrl" character varying(255), "bannerUrl" character varying(255), "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6" UNIQUE ("name"), CONSTRAINT "UQ_0f32d7302e55d3f297c08c1a859" UNIQUE ("prefix"), CONSTRAINT "UQ_1687d82f42d8b3f8162a29e7df4" UNIQUE ("code"), CONSTRAINT "UQ_b15428f362be2200922952dc268" UNIQUE ("slug"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying(500) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid NOT NULL, CONSTRAINT "PK_0586e8a3f1766827efaf0ee3943" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_seos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "metaTitle" character varying(160), "metaDescription" character varying(255), "metaKeywords" character varying(255), "ogTitle" character varying(255), "ogDescription" character varying(255), "ogImage" character varying(255), "twitterCardType" character varying(100), "isIndexable" boolean NOT NULL DEFAULT true, "structuredData" jsonb, "productId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_aa9cd77162626cd7dc1b88dbe3" UNIQUE ("productId"), CONSTRAINT "PK_72070635f0c7d6eb2bbc3c08c4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_physicals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weight" numeric(10,2), "weightUnit" jsonb, "height" numeric(10,2), "width" numeric(10,2), "length" numeric(10,2), "dimensionUnit" jsonb, "isFragile" boolean NOT NULL DEFAULT false, "isPerishable" boolean NOT NULL DEFAULT false, "isEcoFriendly" boolean NOT NULL DEFAULT false, "isBiodegradable" boolean NOT NULL DEFAULT false, "isHazardous" boolean NOT NULL DEFAULT false, "isRequiresRefrigeration" boolean NOT NULL DEFAULT false, "isFlammable" boolean NOT NULL DEFAULT false, "isRequiresAssembly" boolean NOT NULL DEFAULT false, "minStorageTemp" numeric(5,2), "maxStorageTemp" numeric(5,2), "storageTempUnit" jsonb, "material" character varying(50), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid NOT NULL, CONSTRAINT "REL_f40d5610190ba9499035ac46b7" UNIQUE ("productId"), CONSTRAINT "PK_d90d2945609ce33a793e15f66ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_shippings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "freeShipping" boolean NOT NULL DEFAULT false, "handlingDays" integer NOT NULL DEFAULT '0', "packageType" character varying(50), "pickupInStore" boolean NOT NULL DEFAULT false, "specialInstructions" text, "productId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_b0e57b11a849fc8ceeb628ddec" UNIQUE ("productId"), CONSTRAINT "PK_aa0c8dfe1e40305bda2edca3941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "stock" integer DEFAULT '0', "sku" character varying(255), "status" boolean DEFAULT false, "productId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" BIGSERIAL NOT NULL, "categoryId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_53030d3a4b3ba3a7175bb132378" UNIQUE ("code"), CONSTRAINT "PK_bccc8805f3453d0cce77c1beedb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_group_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productGroupId" uuid NOT NULL, "productId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07abafb92bd07cdba526ed4802e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(250) NOT NULL, "slug" character varying(500) NOT NULL, "type" character varying(100) NOT NULL, "code" BIGSERIAL NOT NULL, "quality" smallint NOT NULL DEFAULT '0', "status" character varying NOT NULL, "visibility" character varying NOT NULL, "statusAt" TIMESTAMP, "description" character varying NOT NULL, "extract" character varying NOT NULL, "cover" character varying NOT NULL, "miniature" character varying NOT NULL, "brandId" uuid NOT NULL, "categoryId" uuid NOT NULL, "subcategoryId" uuid NOT NULL, "tags" text, "unitOfMeasure" jsonb, "condition" character varying(100), "warranty" character varying(100), "countryOfOrigin" jsonb, "priceRegular" numeric(10,2) NOT NULL, "priceDiscount" numeric(10,2), "stockQuantity" integer DEFAULT '0', "minStock" integer, "maxStock" integer, "maxOrderLimit" integer, "allowBackorder" boolean NOT NULL DEFAULT false, "reviewsCount" integer NOT NULL DEFAULT '0', "averageRating" numeric(3,2) NOT NULL DEFAULT '0', "viewsCount" integer NOT NULL DEFAULT '0', "salesCount" integer NOT NULL DEFAULT '0', "isBestSeller" boolean NOT NULL DEFAULT false, "isNewArrival" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "isLimitedEdition" boolean NOT NULL DEFAULT false, "isPreOrder" boolean NOT NULL DEFAULT false, "isExportable" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7cfc24d6c24f0ec91294003d6b8" UNIQUE ("code"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_descriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attributeId" uuid NOT NULL, "attributeValueId" uuid NOT NULL, "value" character varying(100) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid NOT NULL, CONSTRAINT "PK_8448465bc4faa6348b235d9b087" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" character varying(150) NOT NULL, "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "attributeId" uuid NOT NULL, CONSTRAINT "PK_3babf93d1842d73e7ba849c0160" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" character varying(250), "attributeGroupId" uuid, "unit" text, "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_89afb34fd1fdb2ceb1cea6c57df" UNIQUE ("name"), CONSTRAINT "PK_32216e2e61830211d3a5d7fa72c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" character varying(250) NOT NULL, "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cbf1498cdad86915f4906d2da6b" UNIQUE ("name"), CONSTRAINT "PK_8cc9117a38fac400f6587812975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attributeGroupId" uuid NOT NULL, "categoryId" uuid NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ec26bb4c14f372881793b1884a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prefix" character varying NOT NULL, "code" BIGSERIAL NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(500) NOT NULL, "icon" character varying(2000), "description" character varying(2000) NOT NULL, "isDimensions" boolean NOT NULL DEFAULT false, "isCharacteristics" boolean NOT NULL DEFAULT false, "isConditiom" boolean NOT NULL DEFAULT false, "isWarranty" boolean NOT NULL DEFAULT false, "isCountryOfOrigin" boolean NOT NULL DEFAULT false, "isMaterial" boolean NOT NULL DEFAULT false, "isTemperature" boolean NOT NULL DEFAULT false, "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f8cfddd595b07a0726c55a22d8" UNIQUE ("prefix"), CONSTRAINT "UQ_77d7eff8a7aaa05457a12b8007a" UNIQUE ("code"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subcategories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100), "prefix" character varying NOT NULL, "code" BIGSERIAL NOT NULL, "slug" character varying(500), "icon" character varying(2000), "status" boolean NOT NULL DEFAULT false, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "categoryId" uuid NOT NULL, CONSTRAINT "UQ_ed13bca77ebe87d6dd663ae2a06" UNIQUE ("prefix"), CONSTRAINT "UQ_83d2c895ee7bbb623cc71aabe53" UNIQUE ("code"), CONSTRAINT "PK_793ef34ad0a3f86f09d4837007c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "collaborators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "names" character varying(100) NOT NULL, "surname" character varying(100) NOT NULL, "fullnames" character varying(100), "type_document" character varying(100), "number_document" character varying(25) NOT NULL, "email" character varying(100) NOT NULL, "password" character varying(200) NOT NULL, "prefix" character varying DEFAULT '+51', "phone" character varying(20), "role" character varying(200), "status" boolean NOT NULL DEFAULT true, "lastDatelogin" TIMESTAMP, "statusAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f579a5df9d66287f400806ad875" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "product_photos" ADD CONSTRAINT "FK_9c18967daa2898d149078cb8282" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_seos" ADD CONSTRAINT "FK_aa9cd77162626cd7dc1b88dbe34" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_physicals" ADD CONSTRAINT "FK_f40d5610190ba9499035ac46b7f" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_shippings" ADD CONSTRAINT "FK_b0e57b11a849fc8ceeb628ddec9" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_groups" ADD CONSTRAINT "FK_b46f61db7a51c6a647cfc874cda" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_group_items" ADD CONSTRAINT "FK_22370b16053aa1cc1c811793aa0" FOREIGN KEY ("productGroupId") REFERENCES "product_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_group_items" ADD CONSTRAINT "FK_7b78a18c416277a1f9f441da3b9" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_7527f75cb36bea4b7f2b86f7d1d" FOREIGN KEY ("subcategoryId") REFERENCES "subcategories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" ADD CONSTRAINT "FK_89f08ce8a98d50a29ebabf0c5ca" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" ADD CONSTRAINT "FK_b23b3131625d89278ee3f613824" FOREIGN KEY ("attributeId") REFERENCES "attributes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" ADD CONSTRAINT "FK_d933954dd589a60b17036e12ac2" FOREIGN KEY ("attributeValueId") REFERENCES "attribute_values"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD CONSTRAINT "FK_b8f8e1d9141248b538c9285574e" FOREIGN KEY ("attributeId") REFERENCES "attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD CONSTRAINT "FK_f66ebcd0ee1a3f090d6fae0c222" FOREIGN KEY ("attributeGroupId") REFERENCES "attribute_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_categories" ADD CONSTRAINT "FK_af47eb28ce21a4fa964cbd6f017" FOREIGN KEY ("attributeGroupId") REFERENCES "attribute_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_categories" ADD CONSTRAINT "FK_a4369ccc2282b6e34371a98087c" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "FK_d1fe096726c3c5b8a500950e448" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "FK_d1fe096726c3c5b8a500950e448"`);
        await queryRunner.query(`ALTER TABLE "attribute_categories" DROP CONSTRAINT "FK_a4369ccc2282b6e34371a98087c"`);
        await queryRunner.query(`ALTER TABLE "attribute_categories" DROP CONSTRAINT "FK_af47eb28ce21a4fa964cbd6f017"`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP CONSTRAINT "FK_f66ebcd0ee1a3f090d6fae0c222"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP CONSTRAINT "FK_b8f8e1d9141248b538c9285574e"`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" DROP CONSTRAINT "FK_d933954dd589a60b17036e12ac2"`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" DROP CONSTRAINT "FK_b23b3131625d89278ee3f613824"`);
        await queryRunner.query(`ALTER TABLE "product_descriptions" DROP CONSTRAINT "FK_89f08ce8a98d50a29ebabf0c5ca"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_7527f75cb36bea4b7f2b86f7d1d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "product_group_items" DROP CONSTRAINT "FK_7b78a18c416277a1f9f441da3b9"`);
        await queryRunner.query(`ALTER TABLE "product_group_items" DROP CONSTRAINT "FK_22370b16053aa1cc1c811793aa0"`);
        await queryRunner.query(`ALTER TABLE "product_groups" DROP CONSTRAINT "FK_b46f61db7a51c6a647cfc874cda"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "product_shippings" DROP CONSTRAINT "FK_b0e57b11a849fc8ceeb628ddec9"`);
        await queryRunner.query(`ALTER TABLE "product_physicals" DROP CONSTRAINT "FK_f40d5610190ba9499035ac46b7f"`);
        await queryRunner.query(`ALTER TABLE "product_seos" DROP CONSTRAINT "FK_aa9cd77162626cd7dc1b88dbe34"`);
        await queryRunner.query(`ALTER TABLE "product_photos" DROP CONSTRAINT "FK_9c18967daa2898d149078cb8282"`);
        await queryRunner.query(`DROP TABLE "collaborators"`);
        await queryRunner.query(`DROP TABLE "subcategories"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "attribute_categories"`);
        await queryRunner.query(`DROP TABLE "attribute_groups"`);
        await queryRunner.query(`DROP TABLE "attributes"`);
        await queryRunner.query(`DROP TABLE "attribute_values"`);
        await queryRunner.query(`DROP TABLE "product_descriptions"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_group_items"`);
        await queryRunner.query(`DROP TABLE "product_groups"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "product_shippings"`);
        await queryRunner.query(`DROP TABLE "product_physicals"`);
        await queryRunner.query(`DROP TABLE "product_seos"`);
        await queryRunner.query(`DROP TABLE "product_photos"`);
        await queryRunner.query(`DROP TABLE "brands"`);
    }

}
